-- Keep the curated catalog representative without turning it into a rigid taxonomy.
-- Existing canonical rows are refreshed so a partially seeded environment converges
-- on the same names, aliases, and role context.
INSERT INTO public.catalog_skills (slug, name, normalized_name) VALUES
  ('html', 'HTML', 'html'),
  ('css', 'CSS', 'css'),
  ('javascript', 'JavaScript', 'javascript'),
  ('typescript', 'TypeScript', 'typescript'),
  ('react', 'React', 'react'),
  ('nextjs', 'Next.js', 'nextjs'),
  ('nodejs', 'Node.js', 'nodejs'),
  ('git', 'Git', 'git'),
  ('linux', 'Linux', 'linux'),
  ('cybersecurity', 'Cybersecurity', 'cybersecurity'),
  ('network-security', 'Network Security', 'networksecurity'),
  ('owasp', 'OWASP', 'owasp'),
  ('design-systems', 'Design Systems', 'designsystems'),
  ('typography', 'Typography', 'typography'),
  ('visual-design', 'Visual Design', 'visualdesign'),
  ('usability-testing', 'Usability Testing', 'usabilitytesting'),
  ('google-ads', 'Google Ads', 'googleads'),
  ('meta-ads', 'Meta Ads', 'metaads'),
  ('email-marketing', 'Email Marketing', 'emailmarketing'),
  ('campaign-management', 'Campaign Management', 'campaignmanagement'),
  ('marketing-analytics', 'Marketing Analytics', 'marketinganalytics'),
  ('statistics', 'Statistics', 'statistics'),
  ('numpy', 'NumPy', 'numpy'),
  ('etl', 'ETL', 'etl'),
  ('dbt', 'dbt', 'dbt'),
  ('product-roadmapping', 'Product Roadmapping', 'productroadmapping'),
  ('requirements-analysis', 'Requirements Analysis', 'requirementsanalysis'),
  ('customer-research', 'Customer Research', 'customerresearch'),
  ('crm', 'CRM', 'crm'),
  ('customer-success', 'Customer Success', 'customersuccess'),
  ('financial-analysis', 'Financial Analysis', 'financialanalysis'),
  ('budgeting', 'Budgeting', 'budgeting'),
  ('taxation', 'Taxation', 'taxation'),
  ('inventory-management', 'Inventory Management', 'inventorymanagement'),
  ('logistics', 'Logistics', 'logistics'),
  ('vendor-management', 'Vendor Management', 'vendormanagement'),
  ('process-improvement', 'Process Improvement', 'processimprovement'),
  ('interviewing', 'Interviewing', 'interviewing'),
  ('employee-relations', 'Employee Relations', 'employeerelations'),
  ('hris', 'HRIS', 'hris'),
  ('public-relations', 'Public Relations', 'publicrelations'),
  ('internal-communications', 'Internal Communications', 'internalcommunications')
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  normalized_name = EXCLUDED.normalized_name,
  is_active = TRUE;

INSERT INTO public.catalog_skill_aliases (skill_id, alias, normalized_alias)
SELECT skill.id, alias.alias, alias.normalized_alias
FROM (VALUES
  ('html', 'HTML5', 'html5'),
  ('css', 'CSS3', 'css3'),
  ('javascript', 'JS', 'js'),
  ('javascript', 'ECMAScript', 'ecmascript'),
  ('typescript', 'TS', 'ts'),
  ('react', 'ReactJS', 'reactjs'),
  ('react', 'React.js', 'react.js'),
  ('nextjs', 'NextJS', 'nextjs'),
  ('nodejs', 'NodeJS', 'nodejs'),
  ('nodejs', 'Node', 'node'),
  ('git', 'Git SCM', 'gitscm'),
  ('cybersecurity', 'Cyber Security', 'cybersecurity'),
  ('network-security', 'Network Sec', 'networksec'),
  ('google-ads', 'Google AdWords', 'googleadwords'),
  ('meta-ads', 'Facebook Ads', 'facebookads'),
  ('marketing-analytics', 'Marketing Data Analysis', 'marketingdataanalysis'),
  ('statistics', 'Statistical Analysis', 'statisticalanalysis'),
  ('etl', 'Extract Transform Load', 'extracttransformload'),
  ('product-roadmapping', 'Product Roadmap', 'productroadmap'),
  ('requirements-analysis', 'Requirement Analysis', 'requirementanalysis'),
  ('crm', 'Customer Relationship Management', 'customerrelationshipmanagement'),
  ('hris', 'Human Resources Information System', 'humanresourcesinformationsystem'),
  ('public-relations', 'PR', 'pr')
) AS alias(skill_slug, alias, normalized_alias)
JOIN public.catalog_skills AS skill ON skill.slug = alias.skill_slug
ON CONFLICT (normalized_alias) DO UPDATE SET
  skill_id = EXCLUDED.skill_id,
  alias = EXCLUDED.alias;

INSERT INTO public.career_role_skills (role_id, skill_id, sort_order)
SELECT role.id, skill.id, relation.sort_order
FROM (VALUES
  ('frontend-engineer', 'html', 10),
  ('frontend-engineer', 'css', 20),
  ('frontend-engineer', 'javascript', 30),
  ('frontend-engineer', 'typescript', 40),
  ('frontend-engineer', 'react', 50),
  ('frontend-engineer', 'nextjs', 60),
  ('frontend-engineer', 'git', 70),
  ('backend-engineer', 'nodejs', 10),
  ('backend-engineer', 'git', 60),
  ('full-stack-engineer', 'nextjs', 50),
  ('full-stack-engineer', 'git', 60),
  ('qa-engineer', 'git', 50),
  ('devops-engineer', 'linux', 10),
  ('devops-engineer', 'git', 60),
  ('mobile-engineer', 'git', 50),
  ('cybersecurity-analyst', 'cybersecurity', 10),
  ('cybersecurity-analyst', 'network-security', 20),
  ('cybersecurity-analyst', 'linux', 30),
  ('cybersecurity-analyst', 'owasp', 40),
  ('graphic-designer', 'typography', 40),
  ('graphic-designer', 'visual-design', 50),
  ('ui-designer', 'design-systems', 50),
  ('ui-designer', 'visual-design', 60),
  ('ux-designer', 'usability-testing', 50),
  ('product-designer', 'design-systems', 50),
  ('product-designer', 'usability-testing', 60),
  ('digital-marketing-specialist', 'google-ads', 50),
  ('digital-marketing-specialist', 'meta-ads', 60),
  ('digital-marketing-specialist', 'marketing-analytics', 70),
  ('seo-specialist', 'marketing-analytics', 40),
  ('social-media-specialist', 'meta-ads', 40),
  ('brand-marketing-specialist', 'campaign-management', 40),
  ('content-marketing-specialist', 'content-strategy', 10),
  ('content-marketing-specialist', 'copywriting', 20),
  ('content-marketing-specialist', 'seo', 30),
  ('content-marketing-specialist', 'email-marketing', 40),
  ('data-analyst', 'statistics', 50),
  ('data-scientist', 'numpy', 50),
  ('data-scientist', 'statistics', 60),
  ('data-engineer', 'etl', 50),
  ('data-engineer', 'dbt', 60),
  ('product-manager', 'product-roadmapping', 50),
  ('product-manager', 'customer-research', 60),
  ('business-analyst', 'requirements-analysis', 50),
  ('customer-success-specialist', 'customer-success', 10),
  ('customer-success-specialist', 'crm', 20),
  ('customer-success-specialist', 'communication', 30),
  ('customer-success-specialist', 'customer-research', 40),
  ('financial-analyst', 'financial-analysis', 40),
  ('financial-analyst', 'budgeting', 50),
  ('accountant', 'taxation', 40),
  ('operations-analyst', 'process-improvement', 40),
  ('supply-chain-analyst', 'inventory-management', 40),
  ('supply-chain-analyst', 'logistics', 50),
  ('procurement-specialist', 'vendor-management', 40),
  ('recruiter', 'interviewing', 40),
  ('recruiter', 'hris', 50),
  ('hr-generalist', 'employee-relations', 40),
  ('hr-generalist', 'hris', 50),
  ('communications-specialist', 'public-relations', 40),
  ('communications-specialist', 'internal-communications', 50)
) AS relation(role_slug, skill_slug, sort_order)
JOIN public.career_roles AS role ON role.slug = relation.role_slug
JOIN public.catalog_skills AS skill ON skill.slug = relation.skill_slug
ON CONFLICT (role_id, skill_id) DO UPDATE SET
  sort_order = EXCLUDED.sort_order;
