export const jobs = [
  {
    id: "nusa-frontend",
    title: "Frontend Developer",
    company: "Nusa Digital",
    initials: "ND",
    source: "LinkedIn",
    location: "Jakarta Selatan",
    arrangement: "Hybrid",
    employmentType: "Penuh waktu",
    postedAt: "Dipublikasikan 4 hari lalu",
    status: "Sudah dianalisis",
    statusTone: "analyzed",
    requirementCount: 5,
    updatedAt: "Dianalisis 2 jam lalu",
  },
  {
    id: "pixel-ui",
    title: "UI Engineer",
    company: "PixelWorks",
    initials: "PW",
    source: "Glints",
    location: "Bandung",
    arrangement: "Remote",
    employmentType: "Penuh waktu",
    postedAt: "Dipublikasikan 1 minggu lalu",
    status: "Siap direview",
    statusTone: "review",
    requirementCount: 8,
    updatedAt: "Disimpan kemarin",
  },
  {
    id: "karya-web",
    title: "Web Developer",
    company: "Karya Labs",
    initials: "KL",
    source: "Kalibrr",
    location: "Jakarta Pusat",
    arrangement: "On-site",
    employmentType: "Kontrak",
    postedAt: "Dipublikasikan 3 hari lalu",
    status: "Draft tersimpan",
    statusTone: "draft",
    requirementCount: 0,
    updatedAt: "Diperbarui 2 hari lalu",
  },
  {
    id: "gojek-frontend",
    title: "Frontend Engineer",
    company: "Gojek",
    initials: "GJ",
    source: "LinkedIn",
    location: "Jakarta Selatan",
    arrangement: "Hybrid",
    employmentType: "Penuh waktu",
    postedAt: "Dipublikasikan 6 hari lalu",
    status: "Siap direview",
    statusTone: "review",
    requirementCount: 11,
    updatedAt: "Disimpan 3 hari lalu",
  },
  {
    id: "tokopedia-frontend",
    title: "Software Engineer, Frontend",
    company: "Tokopedia",
    initials: "TP",
    source: "Career Site",
    location: "Jakarta Selatan",
    arrangement: "Remote",
    employmentType: "Penuh waktu",
    postedAt: "Dipublikasikan 2 minggu lalu",
    status: "Draft tersimpan",
    statusTone: "draft",
    requirementCount: 0,
    updatedAt: "Disimpan 5 hari lalu",
  },
  {
    id: "traveloka-web",
    title: "Web Platform Engineer",
    company: "Traveloka",
    initials: "TV",
    source: "LinkedIn",
    location: "Tangerang",
    arrangement: "Hybrid",
    employmentType: "Penuh waktu",
    postedAt: "Dipublikasikan 3 minggu lalu",
    status: "Sudah dianalisis",
    statusTone: "analyzed",
    requirementCount: 9,
    updatedAt: "Dianalisis 1 minggu lalu",
  },
] as const;

export type MockJob = (typeof jobs)[number];
